# Generated by Django 6.0.4 on 2026-04-18 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('ts3_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='TS3 ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('player_class', models.CharField(blank=True, choices=[('var', 'Воин'), ('mag', 'Маг'), ('luk', 'Лучник'), ('zhrec', 'Жрец'), ('obor', 'Оборотень'), ('dru', 'Друид'), ('sin', 'Син'), ('sham', 'Шаман'), ('mist', 'Мистик'), ('strazh', 'Страж'), ('pal', 'Паладин'), ('strel', 'Стрелок'), ('priz', 'Призрак'), ('zhnec', 'Жнец'), ('makaka', 'Странник'), ('bard', 'Бард'), ('dk', 'Дух крови')], max_length=20, null=True, verbose_name='Класс персонажа')),
                ('hp', models.IntegerField(default=0, verbose_name='❤️ HP')),
                ('mp', models.IntegerField(default=0, verbose_name='💧 MP')),
                ('pa', models.IntegerField(default=0, verbose_name='ПА - Показатель Атаки')),
                ('fa', models.IntegerField(default=0, verbose_name='ФА - Физическая атака')),
                ('ma', models.IntegerField(default=0, verbose_name='МА - Магическая атака')),
                ('pz', models.IntegerField(default=0, verbose_name='ПЗ - Показатель защиты')),
                ('bd', models.IntegerField(default=0, verbose_name='БД - Боевой дух')),
                ('bu', models.IntegerField(default=0, verbose_name='БУ - Бонус уровня')),
                ('physical_defense', models.IntegerField(default=0, verbose_name='Физическая защита')),
                ('magic_defense', models.IntegerField(default=0, verbose_name='Магическая защита')),
                ('physical_pierce', models.IntegerField(default=0, verbose_name='Физический пробив')),
                ('magic_pierce', models.IntegerField(default=0, verbose_name='Магический пробив')),
                ('crit_damage', models.IntegerField(default=0, verbose_name='Крит. урон')),
                ('crit_chance', models.IntegerField(default=0, verbose_name='Крит. шанс')),
                ('accuracy', models.IntegerField(default=0, verbose_name='Меткость')),
                ('dodge', models.IntegerField(default=0, verbose_name='Уклонение')),
                ('activity_points', models.IntegerField(default=0, help_text='Изменяется только в админ-панели', verbose_name='Очки активности')),
                ('spent_points', models.IntegerField(default=0, help_text='Общее количество потраченных очков', verbose_name='Потрачено очков активности')),
                ('earned_points', models.IntegerField(default=0, help_text='Общее количество начисленных очков', verbose_name='Начислено очков активности')),
                ('last_activity', models.DateTimeField(auto_now=True, null=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'редактировать профиль',
                'verbose_name_plural': 'редактировать профили',
            },
        ),
    ]
