# Generated by Django 6.0.4 on 2026-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bu',
            field=models.IntegerField(default=0, verbose_name='БУ - Бонус уровня'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pa',
            field=models.IntegerField(default=0, verbose_name='ПА - Показатель Атаки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pz',
            field=models.IntegerField(default=0, verbose_name='ПЗ - Показатель защиты'),
        ),
    ]
