# Generated by Django 6.0.4 on 2026-04-20 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Последняя активность'),
        ),
    ]
