# Generated by Django 6.0.4 on 2026-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_bu_alter_profile_pa_alter_profile_pz'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fa',
            field=models.IntegerField(default=0, verbose_name='ФА - Физическая атака'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bd',
            field=models.IntegerField(default=0, verbose_name='БД - Боевой дух'),
        ),
    ]
