# Generated by Django 6.0.4 on 2026-04-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_fa_alter_profile_bd'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spent_points',
            field=models.IntegerField(default=0, help_text='Общее количество потраченных очков', verbose_name='Потрачено очков активности'),
        ),
    ]
