# Generated by Django 6.0.4 on 2026-04-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_spent_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Таблица активности', 'verbose_name_plural': 'Таблица активности'},
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Последняя активность'),
        ),
    ]
