# Generated by Django 6.0.4 on 2026-04-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_options_profile_last_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'редактировать профиль', 'verbose_name_plural': 'редактировать профили'},
        ),
    ]
