# Generated by Django 6.0.4 on 2026-04-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='earned_points',
            field=models.IntegerField(default=0, help_text='Общее количество начисленных очков', verbose_name='Начислено очков активности'),
        ),
    ]
