# Generated by Django 6.0.4 on 2026-04-30 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0003_subcategory_is_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа ивента')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('parties_count', models.PositiveIntegerField(default=1, help_text='Сколько отрядов в ивенте', verbose_name='Количество отрядов')),
                ('party_size', models.PositiveIntegerField(default=10, help_text='Количество участников в отряде (включая лидера)', verbose_name='Размер отряда')),
                ('icon', models.CharField(default='⚔️', max_length=10, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forum_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='forum.subcategory', verbose_name='Подкатегория форума')),
            ],
            options={
                'verbose_name': 'Тип ивента',
                'verbose_name_plural': 'Типы ивентов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата проведения')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('sent_to_users', models.ManyToManyField(blank=True, related_name='event_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправлено пользователям')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.eventtype', verbose_name='Тип ивента')),
            ],
            options={
                'verbose_name': 'Уведомление об ивенте',
                'verbose_name_plural': 'Уведомления об ивентах',
                'ordering': ['-event_date', '-sent_at'],
                'unique_together': {('event_type', 'event_date')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Особенности на эту неделю', verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventtype', verbose_name='Тип ивента')),
            ],
            options={
                'verbose_name': 'Ивент',
                'verbose_name_plural': 'Ивенты',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер отряда')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='events.event')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_parties', to=settings.AUTH_USER_MODEL, verbose_name='Лидер отряда')),
            ],
            options={
                'verbose_name': 'Отряд',
                'verbose_name_plural': 'Отряды',
                'ordering': ['event', 'number'],
                'unique_together': {('event', 'number')},
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', '✅ Приду'), ('no', '❌ Не приду'), ('maybe', '🤔 Возможно')], max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.eventnotification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Ответ на уведомление',
                'verbose_name_plural': 'Ответы на уведомления',
                'unique_together': {('notification', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='events.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник отряда',
                'verbose_name_plural': 'Участники отрядов',
                'unique_together': {('party', 'user')},
            },
        ),
    ]
