# Generated by Django 6.0.4 on 2026-04-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Слаг'),
        ),
    ]
