# Generated by Django 6.0.4 on 2026-04-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_dummymodel'),
        ('events', '0002_alter_eventtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnotification',
            name='recipient_groups',
            field=models.ManyToManyField(blank=True, help_text='Выберите группы пользователей, которые получат уведомление. Если не выбрано - отправляется всем членам гильдии', to='auth.group', verbose_name='Группы получателей'),
        ),
        migrations.AlterField(
            model_name='eventnotification',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Отправлено'),
        ),
    ]
