# Generated by Django 6.0.4 on 2026-04-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category', 'order', 'title'], 'verbose_name': 'Подкатегорию', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='Чем меньше число, тем выше категория в списке. 0 = сортировка по алфавиту', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Чем меньше число, тем выше подкатегория в списке. 0 = сортировка по алфавиту', verbose_name='Порядок сортировки'),
        ),
    ]
