# Generated by Django 6.0.4 on 2026-04-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_events',
            field=models.BooleanField(default=False, help_text='Отметьте, если эта подкатегория предназначена для отображения ивентов', verbose_name='Это ивентовая подкатегория'),
        ),
    ]
