# Generated by Django 6.0.4 on 2026-04-14 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forum', '0004_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Тему', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='category',
            name='view_groups',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым для доступа всем пользователям', to='auth.group', verbose_name='Группы с доступом'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='view_groups',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым для доступа всем пользователям', to='auth.group', verbose_name='Группы с доступом'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.subcategory', verbose_name='Подкатегории'),
        ),
    ]
