# Generated by Django 6.0.4 on 2026-04-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_reception',
            field=models.BooleanField(default=False, help_text='Отметьте, если эта подкатегория предназначена для приема заявок в гильдию', verbose_name='Это прием заявок'),
        ),
    ]
