# Generated by Django 6.0.4 on 2026-04-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forum', '0005_alter_topic_options_category_view_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='require_auth',
            field=models.BooleanField(default=False, help_text='Если включено, категорию видят только авторизованные пользователи', verbose_name='Только для авторизованных'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='require_auth',
            field=models.BooleanField(default=False, help_text='Если включено, подкатегорию видят только авторизованные пользователи', verbose_name='Только для авторизованных'),
        ),
        migrations.AlterField(
            model_name='category',
            name='view_groups',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым для доступа всем пользователям (с учетом require_auth)', to='auth.group', verbose_name='Группы с доступом'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='view_groups',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым для доступа всем пользователям (с учетом require_auth)', to='auth.group', verbose_name='Группы с доступом'),
        ),
    ]
