# Generated by Django 6.0.4 on 2026-04-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_subcategory_is_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_reception_view',
            field=models.BooleanField(default=False, help_text='Отметьте, если эта подкатегория для ПРОСМОТРА и ГОЛОСОВАНИЯ за заявки (доступно только членам гильдии)', verbose_name='Это просмотр заявок'),
        ),
    ]
