# Generated by Django 6.0.4 on 2026-04-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_category_require_auth_subcategory_require_auth_and_more'),
    ]

    operations = [
    ]
