# Generated by Django 6.0.4 on 2026-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20260415_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_auction',
            field=models.BooleanField(default=False, help_text='Отметьте, если эта подкатегория является аукционом', verbose_name='Это аукцион'),
        ),
    ]
