# Generated by Django 6.0.4 on 2026-04-16 13:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название лота')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon_choice', models.CharField(choices=[('wheel_of_fate', 'Колесо Судьбы'), ('stone_of_universe', 'Камень мироздания'), ('opal', 'Опал Лунной Кошки'), ('divinity_stone', 'Камень божества'), ('great_meteorite', 'Великий метеорит'), ('rune_set_7', 'Набор рун (7ур)'), ('time_yarn', 'Пряжа времени'), ('rune_set_9', 'Набор рун 9 ур'), ('absolute_stones', 'Камни абсолюта'), ('custom', 'Своя картинка')], default='custom', help_text='Выберите иконку или "Своя картинка" для загрузки своего изображения', max_length=30, verbose_name='Выбор иконки')),
                ('custom_image', models.ImageField(blank=True, help_text='Загрузите свою картинку (только если выбрано "Своя картинка")', null=True, upload_to='auction/lots/', verbose_name='Своя картинка')),
                ('initial_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Начальная цена')),
                ('current_price', models.IntegerField(default=0, verbose_name='Текущая цена')),
                ('min_step', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимальный шаг ставки')),
                ('max_winners', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум победителей')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('ended', 'Завершен'), ('cancelled', 'Отменен')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Аукционный лот',
                'verbose_name_plural': 'Аукционные лоты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма ставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ставки')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Победитель')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auctionlot')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ['-bid_amount', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('credit', 'Начисление'), ('debit', 'Списание')], max_length=10, verbose_name='Тип')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время операции')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='auction.auctionlot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
