# Generated by Django 6.0.4 on 2026-04-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlot',
            name='subcategory',
        ),
    ]
