# Generated by Django 6.0.4 on 2026-04-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Очки заморожены'),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('frozen', 'Заморожена'), ('won', 'Выиграна'), ('lost', 'Проиграна')], default='active', max_length=10, verbose_name='Статус ставки'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Начисление'), ('debit', 'Списание'), ('freeze', 'Заморозка'), ('unfreeze', 'Разморозка')], max_length=10, verbose_name='Тип'),
        ),
    ]
