# Generated by Django 6.0.4 on 2026-04-27 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlot',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='auctionlot',
            name='ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_auctions', to=settings.AUTH_USER_MODEL, verbose_name='Завершил'),
        ),
        migrations.AlterField(
            model_name='auctionbid',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('frozen', 'Заморожена'), ('won', 'Выиграна'), ('lost', 'Проиграна'), ('outbid', 'Перебита'), ('cancelled', 'Отменена')], default='active', max_length=10, verbose_name='Статус ставки'),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Плановая дата окончания (только для информации)', null=True, verbose_name='Дата окончания (план)'),
        ),
    ]
