# Generated by Django 6.0.4 on 2026-04-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auctionlot_ended_at_auctionlot_ended_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlot',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Плановая дата окончания. После этой даты ставки будут запрещены до завершения админом', null=True, verbose_name='Дата окончания (план)'),
        ),
    ]
