# Generated by Django 6.0.4 on 2026-04-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auctionbid_is_frozen_auctionbid_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlot',
            name='max_winners',
        ),
        migrations.AlterField(
            model_name='auctionbid',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('frozen', 'Заморожена'), ('won', 'Выиграна'), ('lost', 'Проиграна'), ('outbid', 'Перебита')], default='active', max_length=10, verbose_name='Статус ставки'),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
