# Generated by Django 6.0.4 on 2026-04-17 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_class', models.CharField(max_length=20, verbose_name='Класс персонажа')),
                ('previous_nicknames', models.TextField(blank=True, help_text='Укажите все прошлые никнеймы, если были', verbose_name='Прошлые никнеймы')),
                ('timezone', models.CharField(default='UTC+3', max_length=50, verbose_name='Часовой пояс')),
                ('real_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('on_blacklist', models.BooleanField(default=False, help_text='Отметьте, если вы находитесь в черном списке других гильдий', verbose_name='Нахождение в ЧС других гильдий')),
                ('blacklist_details', models.TextField(blank=True, help_text='Если вы в ЧС, укажите причину и какие гильдии', verbose_name='Пояснение по ЧС')),
                ('other_guilds', models.TextField(blank=True, help_text='Перечислите все гильдии, в которых вы сейчас состоите', verbose_name='Гильдии в которых состоит')),
                ('development_plans', models.TextField(help_text='Опишите свои ближайшие планы по развитию персонажа', verbose_name='Планы на развитие персонажа на 2 месяца')),
                ('guarantors', models.TextField(blank=True, help_text='Укажите поручителей, если они есть (никнеймы)', verbose_name='Поручители')),
                ('screenshot1', models.ImageField(blank=True, null=True, upload_to='applications/screenshots/%Y/%m/%d/', verbose_name='Скриншот 1')),
                ('screenshot2', models.ImageField(blank=True, null=True, upload_to='applications/screenshots/%Y/%m/%d/', verbose_name='Скриншот 2')),
                ('screenshot3', models.ImageField(blank=True, null=True, upload_to='applications/screenshots/%Y/%m/%d/', verbose_name='Скриншот 3')),
                ('screenshot4', models.ImageField(blank=True, null=True, upload_to='applications/screenshots/%Y/%m/%d/', verbose_name='Скриншот 4')),
                ('screenshot5', models.ImageField(blank=True, null=True, upload_to='applications/screenshots/%Y/%m/%d/', verbose_name='Скриншот 5')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('voting', 'Голосование')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('for', 'За'), ('against', 'Против'), ('abstain', 'Воздержался')], max_length=10, verbose_name='Голос')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата голосования')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reception.application')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'unique_together': {('application', 'voter')},
            },
        ),
    ]
