# Generated by Django 6.0.4 on 2026-04-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='blacklist_details',
            field=models.TextField(blank=True, verbose_name='Пояснение по ЧС'),
        ),
        migrations.AlterField(
            model_name='application',
            name='development_plans',
            field=models.TextField(verbose_name='Планы на развитие персонажа на 2 месяца'),
        ),
        migrations.AlterField(
            model_name='application',
            name='guarantors',
            field=models.TextField(blank=True, verbose_name='Поручители'),
        ),
        migrations.AlterField(
            model_name='application',
            name='on_blacklist',
            field=models.BooleanField(default=False, verbose_name='Нахождение в ЧС других гильдий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_guilds',
            field=models.TextField(blank=True, verbose_name='Гильдии в которых состоит'),
        ),
    ]
