# Generated by Django 6.0.4 on 2026-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название гильдии')),
                ('url_obs', models.URLField(blank=True, verbose_name='Ссылка на гильдию')),
            ],
            options={
                'verbose_name': 'Гильдия',
                'verbose_name_plural': 'Гильдии',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ник персонажа')),
                ('player_class', models.CharField(choices=[('var', 'Воин'), ('mag', 'Маг'), ('luk', 'Лучник'), ('zhrec', 'Жрец'), ('obor', 'Оборотень'), ('dru', 'Друид'), ('sin', 'Син'), ('sham', 'Шаман'), ('mist', 'Мистик'), ('strazh', 'Страж'), ('pal', 'Паладин'), ('strel', 'Стрелок'), ('priz', 'Призрак'), ('zhnec', 'Жнец'), ('makaka', 'Странник'), ('bard', 'Бард'), ('dk', 'Дух крови')], max_length=20, verbose_name='Класс персонажа')),
                ('url_obs', models.CharField(blank=True, verbose_name='Ссылка на персонажа')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ('name',),
            },
        ),
    ]
