# Generated by Django 6.0.4 on 2026-04-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guild',
            options={'ordering': ('name',), 'verbose_name': 'Гильдию', 'verbose_name_plural': 'Гильдии'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('name',), 'verbose_name': 'Игрока', 'verbose_name_plural': 'Игроки'},
        ),
    ]
